name: Tests
on:
  push:
    branches-ignore:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: cat /proc/meminfo
      - uses: styfle/cancel-workflow-action@0.11.0
      - run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .nvmrc
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: docker compose up --wait
      - run: docker exec keeper-wallet-extension-chrome-1 cat /proc/meminfo
      - run: yarn test
      - if: ${{ always() }}
        uses: jwalton/gh-docker-logs@v2.2.0
      - if: ${{ always() }}
        run: docker compose down
      - if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: video
          path: test/videos
